databases:
  - name: gastos-hormiga-db
    plan: free
    databaseName: gastos_hormiga
    user: gastos_user

services:
  - type: web
    name: gastos-hormiga-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build && npm run db:push
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: gastos-hormiga-db
          property: connectionString
